import type { MenuPageData } from "@/types/menu";

export const mockMenuData: MenuPageData = {
  settings: {
    _id: "settings",
    name: "mon nom",
    decorativeLogoText: "mon\nnom",
    description: "Bakery, śniadania, kawa.",
    address: "ul. Przykładowa 12, Warszawa",
    phone: "+48 500 100 200",
    email: "hello@monnom.pl",
    instagramUrl: "https://instagram.com/monnom",
    reservationUrl: "https://monnom.pl/rezerwacje",
    openingHoursWeekdays: "10:00 - 15:00",
    openingHoursWeekend: "9:00 - 15:00",
    footerNote: "Zamówienie można złożyć przy kasie",
    seoTitle: "Mon Nom Bakery Menu",
    seoDescription: "Minimalne menu śniadaniowe Mon Nom Bakery.",
  },
  groups: [
    {
      _id: "group-breakfast",
      title: "Menu",
      slug: "menu",
      order: 1,
      isVisible: true,
    },
  ],
  categories: [
    {
      _id: "cat-breakfast",
      title: "Śniadania",
      slug: "sniadania",
      group: { _type: "reference", _ref: "group-breakfast" },
      order: 1,
      isVisible: true,
    },
    {
      _id: "cat-porridge",
      title: "Owsianki",
      slug: "owsianki",
      group: { _type: "reference", _ref: "group-breakfast" },
      order: 2,
      isVisible: true,
    },
    {
      _id: "cat-sandwiches",
      title: "Sandwicze",
      slug: "sandwicze",
      group: { _type: "reference", _ref: "group-breakfast" },
      order: 3,
      isVisible: true,
    },
    {
      _id: "cat-plates",
      title: "Talerze",
      slug: "talerze",
      group: { _type: "reference", _ref: "group-breakfast" },
      order: 4,
      isVisible: true,
    },
    {
      _id: "cat-sweet",
      title: "Słodkie",
      slug: "slodkie",
      group: { _type: "reference", _ref: "group-breakfast" },
      order: 5,
      isVisible: true,
    },
  ],
  items: [
    {
      _id: "item-mortadela",
      name: "Śniadanie Mortadela",
      slug: "sniadanie-mortadela",
      category: { _type: "reference", _ref: "cat-breakfast" },
      description: "chleb, jajecznica, ser, mortadela, dżem, masło, sałatka",
      price: "33",
      isVisible: true,
      isAvailable: true,
      isFeatured: false,
      order: 1,
    },
    {
      _id: "item-losos",
      name: "Śniadanie Łosoś",
      slug: "sniadanie-losos",
      category: { _type: "reference", _ref: "cat-breakfast" },
      description: "chleb, jajecznica, awokado, łosoś, dżem, masło, sałatka",
      price: "39",
      tags: ["nowe"],
      isVisible: true,
      isAvailable: true,
      isFeatured: true,
      order: 2,
    },
    {
      _id: "item-owsianka-mortadela",
      name: "Owsianka Mortadela & Jajko",
      slug: "owsianka-mortadela-jajko",
      category: { _type: "reference", _ref: "cat-porridge" },
      description: "owsianka z sosem sojowym i pastą orzechową, mortadela, jajko",
      price: "30",
      isVisible: true,
      isAvailable: true,
      isFeatured: false,
      order: 1,
    },
    {
      _id: "item-owsianka-losos",
      name: "Owsianka Awokado & Łosoś",
      slug: "owsianka-awokado-losos",
      category: { _type: "reference", _ref: "cat-porridge" },
      description: "owsianka z sosem sojowym i pastą orzechową, awokado, łosoś",
      price: "36",
      isVisible: true,
      isAvailable: true,
      isFeatured: false,
      order: 2,
    },
    {
      _id: "item-roastbeef",
      name: "Sandwicz z rostbefem",
      slug: "sandwicz-z-rostbefem",
      category: { _type: "reference", _ref: "cat-sandwiches" },
      description: "chleb pszenno-żytni, majonez miso, sałata, roastbeef, cebula",
      price: "34",
      isVisible: true,
      isAvailable: true,
      isFeatured: false,
      order: 1,
    },
    {
      _id: "item-indyk",
      name: "Sandwicz z indykiem",
      slug: "sandwicz-z-indykiem",
      category: { _type: "reference", _ref: "cat-sandwiches" },
      description: "ciabatta, jajecznica, indyk, sałata",
      price: "32",
      isVisible: true,
      isAvailable: true,
      isFeatured: false,
      order: 2,
    },
    {
      _id: "item-talerz",
      name: "Talerz jajko i ser",
      slug: "talerz-jajko-i-ser",
      category: { _type: "reference", _ref: "cat-plates" },
      price: "25",
      isVisible: true,
      isAvailable: true,
      isFeatured: false,
      order: 1,
    },
    {
      _id: "item-syrniki-chalwa",
      name: "Syrniki z chałwą",
      slug: "syrniki-z-chalwa",
      category: { _type: "reference", _ref: "cat-sweet" },
      description: "słodki twaróg, chałwa, malina, mleko zagęszczone, śmietana",
      price: "34",
      image: {
        asset: {
          url: "/menu/sample-dish.jpg",
        },
      },
      imageAlt: "Syrniki z chałwą na talerzu",
      isVisible: true,
      isAvailable: true,
      isFeatured: false,
      order: 1,
    },
    {
      _id: "item-syrniki-ogorek",
      name: "Syrniki z salsą ogórkową",
      slug: "syrniki-z-salsa-ogorkowa",
      category: { _type: "reference", _ref: "cat-sweet" },
      description: "solony twaróg, salsa ogórkowa, kolendra, śmietana",
      price: "29",
      isVisible: true,
      isAvailable: true,
      isFeatured: false,
      order: 2,
    },
  ],
};
