import type { MenuPageData } from "@/types/menu";

export const mockMenuData: MenuPageData = {
  settings: {
    _id: "settings",
    name: "mon nom",
    decorativeLogoText: "mon\nnom",
    description: "Bakery, śniadania, kawa.",
    address: "Poznańska 13, 00-680 Warszawa",
    mapUrl: "https://maps.app.goo.gl/Fo9i1xuErkMAw6e66?g_st=ic",
    instagramUrl: "https://www.instagram.com/monnom_bakery?igsh=MW5kMHBnaGJwNXljbw==",
    openingHoursWeekdays: "8:30 - 18:00",
    openingHoursWeekend: "9:00 - 18:00",
    brunchHoursWeekdays: "10:00 - 15:00",
    brunchHoursWeekend: "9:00 - 15:00",
    footerNote: "Zamówienie można złożyć przy kasie",
    seoTitle: "Mon Nom Bakery Menu",
    seoDescription: "Minimalne menu śniadaniowe Mon Nom Bakery.",
  },
  groups: [
    {
      _id: "group-breakfast",
      title: "Menu",
      slug: "menu",
      order: 1,
      isVisible: true,
    },
  ],
  categories: [
    {
      _id: "cat-breakfast",
      title: "Śniadania",
      slug: "sniadania",
      group: { _type: "reference", _ref: "group-breakfast" },
      order: 1,
      isVisible: true,
    },
    {
      _id: "cat-porridge",
      title: "Owsianki",
      slug: "owsianki",
      group: { _type: "reference", _ref: "group-breakfast" },
      order: 2,
      isVisible: true,
    },
    {
      _id: "cat-sandwiches",
      title: "Sandwicze",
      slug: "sandwicze",
      group: { _type: "reference", _ref: "group-breakfast" },
      order: 3,
      isVisible: true,
    },
    {
      _id: "cat-plates",
      title: "Talerze",
      slug: "talerze",
      group: { _type: "reference", _ref: "group-breakfast" },
      order: 4,
      isVisible: true,
    },
    {
      _id: "cat-sweet",
      title: "Słodkie",
      slug: "slodkie",
      group: { _type: "reference", _ref: "group-breakfast" },
      order: 5,
      isVisible: true,
    },
    {
      _id: "cat-coffee",
      title: "Kawa",
      slug: "kawa",
      group: { _type: "reference", _ref: "group-breakfast" },
      order: 6,
      isVisible: true,
    },
    {
      _id: "cat-matcha",
      title: "Matcha",
      slug: "matcha",
      group: { _type: "reference", _ref: "group-breakfast" },
      order: 7,
      isVisible: true,
    },
  ],
  items: [
    {
      _id: "item-mortadela",
      name: "Śniadanie Mortadela",
      slug: "sniadanie-mortadela",
      category: { _type: "reference", _ref: "cat-breakfast" },
      description: "chleb, jajecznica, ser, mortadela, dżem, masło, sałatka",
      price: "33",
      image: {
        asset: {
          url: "/menu/photos/sniadanie-mortadelo.jpeg",
        },
      },
      imageAlt: "Śniadanie z mortadelą, jajecznicą i pieczywem",
      isVisible: true,
      isAvailable: true,
      isFeatured: false,
      order: 1,
    },
    {
      _id: "item-losos",
      name: "Śniadanie Łosoś",
      slug: "sniadanie-losos",
      category: { _type: "reference", _ref: "cat-breakfast" },
      description: "chleb, jajecznica, awokado, łosoś, dżem, masło, sałatka",
      price: "39",
      image: { asset: { url: "/menu/photos/sniadanie-losos.jpeg" } },
      imageAlt: "Śniadanie z łososiem i awokado",
      tags: ["nowe"],
      isVisible: true,
      isAvailable: true,
      isFeatured: true,
      order: 2,
    },
    {
      _id: "item-owsianka-mortadela",
      name: "Owsianka Mortadela & Jajko",
      slug: "owsianka-mortadela-jajko",
      category: { _type: "reference", _ref: "cat-porridge" },
      description: "owsianka z sosem sojowym i pastą orzechową, mortadela, jajko",
      price: "30",
      image: { asset: { url: "/menu/photos/owsianka-mortadelo.jpeg" } },
      imageAlt: "Owsianka z mortadelą i jajkiem",
      isVisible: true,
      isAvailable: true,
      isFeatured: false,
      order: 1,
    },
    {
      _id: "item-owsianka-losos",
      name: "Owsianka Awokado & Łosoś",
      slug: "owsianka-awokado-losos",
      category: { _type: "reference", _ref: "cat-porridge" },
      description: "owsianka z sosem sojowym i pastą orzechową, awokado, łosoś",
      price: "36",
      image: { asset: { url: "/menu/photos/owsianka-losos.jpeg" } },
      imageAlt: "Owsianka z awokado i łososiem",
      isVisible: true,
      isAvailable: true,
      isFeatured: false,
      order: 2,
    },
    {
      _id: "item-roastbeef",
      name: "Sandwicz z rostbefem",
      slug: "sandwicz-z-rostbefem",
      category: { _type: "reference", _ref: "cat-sandwiches" },
      description: "chleb pszenno-żytni, majonez miso, sałata, roastbeef, cebula",
      price: "34",
      image: {
        asset: {
          url: "/menu/photos/sandwicz-rostbef.jpeg",
        },
      },
      imageAlt: "Sandwicz z rostbefem, sałatą i cebulą",
      isVisible: true,
      isAvailable: true,
      isFeatured: false,
      order: 1,
    },
    {
      _id: "item-indyk",
      name: "Sandwicz z indykiem",
      slug: "sandwicz-z-indykiem",
      category: { _type: "reference", _ref: "cat-sandwiches" },
      description: "ciabatta, jajecznica, indyk, sałata",
      price: "32",
      image: { asset: { url: "/menu/photos/sandwicz-indyk.jpeg" } },
      imageAlt: "Sandwicz z indykiem, jajecznicą i sałatą",
      isVisible: true,
      isAvailable: true,
      isFeatured: false,
      order: 2,
    },
    {
      _id: "item-talerz",
      name: "Talerz jajko i ser",
      slug: "talerz-jajko-i-ser",
      category: { _type: "reference", _ref: "cat-plates" },
      price: "25",
      image: { asset: { url: "/menu/photos/talerz-jajko-ser.jpeg" } },
      imageAlt: "Talerz z jajkiem i serem",
      isVisible: true,
      isAvailable: true,
      isFeatured: false,
      order: 1,
    },
    {
      _id: "item-syrniki-chalwa",
      name: "Syrniki z chałwą",
      slug: "syrniki-z-chalwa",
      category: { _type: "reference", _ref: "cat-sweet" },
      description: "słodki twaróg, chałwa, malina, mleko zagęszczone, śmietana",
      price: "34",
      image: {
        asset: {
          url: "/menu/photos/syrniki-chalwa.jpeg",
        },
      },
      imageAlt: "Syrniki z chałwą na talerzu",
      isVisible: true,
      isAvailable: true,
      isFeatured: false,
      order: 1,
    },
    {
      _id: "item-syrniki-ogorek",
      name: "Syrniki z salsą ogórkową",
      slug: "syrniki-z-salsa-ogorkowa",
      category: { _type: "reference", _ref: "cat-sweet" },
      description: "solony twaróg, salsa ogórkowa, kolendra, śmietana",
      price: "29",
      image: { asset: { url: "/menu/photos/syrniki-ogorek.jpeg" } },
      imageAlt: "Syrniki z salsą ogórkową",
      isVisible: true,
      isAvailable: true,
      isFeatured: false,
      order: 2,
    },
    {
      _id: "item-espresso-tonic", name: "Espresso Tonic", slug: "espresso-tonic",
      category: { _type: "reference", _ref: "cat-coffee" }, price: "22",
      image: { asset: { url: "/menu/photos/espresso-tonic.jpeg" } }, imageAlt: "Espresso tonic z lodem",
      isVisible: true, isAvailable: true, isFeatured: false, order: 1,
    },
    {
      _id: "item-citrus-coffee", name: "Citrus Coffee", slug: "citrus-coffee",
      category: { _type: "reference", _ref: "cat-coffee" }, price: "27",
      image: { asset: { url: "/menu/photos/citrus-coffe.jpeg" } }, imageAlt: "Citrus coffee z lodem",
      isVisible: true, isAvailable: true, isFeatured: false, order: 2,
    },
    {
      _id: "item-filter-tonic", name: "Filter Tonic", slug: "filter-tonic",
      category: { _type: "reference", _ref: "cat-coffee" }, price: "22",
      image: { asset: { url: "/menu/photos/filter-tonic.jpeg" } }, imageAlt: "Filter tonic z cytrusem",
      isVisible: true, isAvailable: true, isFeatured: false, order: 3,
    },
    {
      _id: "item-ice-filter", name: "Ice Filter", slug: "ice-filter",
      category: { _type: "reference", _ref: "cat-coffee" }, price: "19",
      image: { asset: { url: "/menu/photos/ice-filter.jpeg" } }, imageAlt: "Kawa filtrowana na lodzie",
      isVisible: true, isAvailable: true, isFeatured: false, order: 4,
    },
    {
      _id: "item-ice-latte-sesame", name: "Ice Latte Sesame", slug: "ice-latte-sesame",
      category: { _type: "reference", _ref: "cat-coffee" }, price: "27",
      image: { asset: { url: "/menu/photos/iced-latte-sesame.jpeg" } }, imageAlt: "Mrożone latte sezamowe",
      isVisible: true, isAvailable: true, isFeatured: false, order: 5,
    },
    {
      _id: "item-tropical-matcha", name: "Tropical Matcha", slug: "tropical-matcha",
      category: { _type: "reference", _ref: "cat-matcha" }, price: "28",
      image: { asset: { url: "/menu/photos/tropical-matcha.jpeg" } }, imageAlt: "Tropikalna matcha z lodem",
      isVisible: true, isAvailable: true, isFeatured: false, order: 1,
    },
    {
      _id: "item-ice-matcha-latte", name: "Ice Matcha Latte", slug: "ice-matcha-latte",
      category: { _type: "reference", _ref: "cat-matcha" }, price: "22",
      image: { asset: { url: "/menu/photos/iced-matcha-latte.jpeg" } }, imageAlt: "Mrożona matcha latte",
      isVisible: true, isAvailable: true, isFeatured: false, order: 2,
    },
    {
      _id: "item-matcha-tonic", name: "Matcha Tonic", slug: "matcha-tonic",
      category: { _type: "reference", _ref: "cat-matcha" }, price: "20",
      image: { asset: { url: "/menu/photos/matcha-tonic.jpeg" } }, imageAlt: "Matcha tonic z lodem",
      isVisible: true, isAvailable: true, isFeatured: false, order: 3,
    },
    {
      _id: "item-ice-matcha-sesame", name: "Ice Matcha Sesame", slug: "ice-matcha-sesame",
      category: { _type: "reference", _ref: "cat-matcha" }, price: "28",
      image: { asset: { url: "/menu/photos/ice-matcha-sesame.jpeg" } }, imageAlt: "Mrożona matcha sezamowa",
      isVisible: true, isAvailable: true, isFeatured: false, order: 4,
    },
  ],
};
