import { defineField, defineType } from "sanity";

export const restaurantSettings = defineType({
  name: "restaurantSettings",
  title: "Restaurant Settings",
  type: "document",
  fields: [
    defineField({ name: "name", type: "string", validation: (rule) => rule.required() }),
    defineField({ name: "logo", type: "image", options: { hotspot: true } }),
    defineField({ name: "decorativeLogo", type: "image", options: { hotspot: true } }),
    defineField({ name: "description", title: "Description (Polish)", type: "text" }),
    defineField({ name: "descriptionEn", title: "Description (English)", type: "text" }),
    defineField({ name: "address", type: "string" }),
    defineField({ name: "mapUrl", type: "url" }),
    defineField({ name: "phone", type: "string" }),
    defineField({ name: "email", type: "string" }),
    defineField({ name: "instagramUrl", type: "url" }),
    defineField({ name: "reservationUrl", type: "url" }),
    defineField({ name: "openingHoursWeekdays", type: "string" }),
    defineField({ name: "openingHoursWeekdaysEn", title: "Opening hours weekdays (English)", type: "string" }),
    defineField({ name: "openingHoursWeekend", type: "string" }),
    defineField({ name: "openingHoursWeekendEn", title: "Opening hours weekend (English)", type: "string" }),
    defineField({ name: "brunchHoursWeekdays", type: "string" }),
    defineField({ name: "brunchHoursWeekdaysEn", title: "Brunch hours weekdays (English)", type: "string" }),
    defineField({ name: "brunchHoursWeekend", type: "string" }),
    defineField({ name: "brunchHoursWeekendEn", title: "Brunch hours weekend (English)", type: "string" }),
    defineField({ name: "footerNote", title: "Footer note (Polish)", type: "string" }),
    defineField({ name: "footerNoteEn", title: "Footer note (English)", type: "string" }),
    defineField({ name: "seoTitle", title: "SEO title (Polish)", type: "string" }),
    defineField({ name: "seoTitleEn", title: "SEO title (English)", type: "string" }),
    defineField({ name: "seoDescription", title: "SEO description (Polish)", type: "text" }),
    defineField({ name: "seoDescriptionEn", title: "SEO description (English)", type: "text" }),
  ],
});
